### ISSUE TITLE
EchLink User Status

### ISSUE THREAD

**Issue by OE9SAU** [f5vmr/SVXLink-Dash-V2#14]
Hi Chris
maybe you can give me a hint to the following question.
Should the dasboard showing the EchoLink Username? 
![EL_Connect](https://github.com/user-attachments/assets/2202a2ad-aef3-4f76-9e03-df8ded724e65
Becasue mine doesnt. Where does the info comming from? Logfile?

Thanks for feedback.

**Comment by f5vmr** [comment]
Hi Martin
The header in the dashboard shows the name of the node held in the ReflectorLogic, not the Echolink name nor the RF Name.

Things get a little complicated, especially as in my nodes - They all identify in RF as G4NAB, but each has a Network Name.
My EchoLink Node identifies as G4NAB on the air, but visible on the network as G4NAB-L, but its EchoLink name is ER-G4NAB.
But you will see it in the Live EchoLink nodes as G4NAB-R, which is the other way round.

I have chosen -R as it’s part of the super-repeater that is the svxreflector.

I hope that assists.


Chris

**Comment by f5vmr** [comment]
To clarify further look at http://svxportal-uk.ddns.net:81 for the various nodes.

**Comment by OE9SAU** [comment]
Hello Chris, thank you for your feedback.
I'm not sure if we're talking about the same thing.The dashboard showing on the left hand side an area called "EchoLink Users". There you can see if someone is connected to the node via EchoLink, right? Thought there i could see the callsign of the currently connected echolink user.
73, Martin (OE9SAU)

**Comment by f5vmr** [comment]
I am sure we are. The box on the left is for incoming connections as you are quite right to note, but no callsign information will be displayed only the number of stations connected, including your own.
This is me connecting to myself with a mobile app. No Callsign is visible, and no traffic appears in the main field.

￼

I’ve included these images to illustrate the CALLSIGN variations. Your callsign at the top of the dashboard is what ever you programmed it at the time of installing. You can change it, by editing the svxlink.conf.
For example in my svxlink.conf in SimplexLogic CALLSIGN=G4NAB

￼
,
 but in ReflectorLogic CALLSIGN=G4NAB-L. 

￼
 
And In ModuleEcholink.conf CALLSIGN=G4NAB-R

￼

In the [Location] field CALLSIGN=ER-G4NAB is set and treated for the unique benefit of svxlink only, this was in the original programming by Tobias SM0SVX.

But the only place it seems the call sign of the connecting station will be in the Log display. Maybe I’ll think of a way to display this in the main window, but it’s not easy, it will be new code.


73

Chris G4NAB

**Comment by OE9SAU** [comment]
Hey Chris, many thanks for the detailed explanation. Now its clear. All the best and 73. Martin OE9SAU
