### ISSUE TITLE
 Failed opening '../parse_svxconf.php' in apache2. error.log

### ISSUE THREAD

**Issue by bi7jta** [f5vmr/SVXLink-Dash-V2#4]
OS: Raspberry Pi 4B2G,  Bullseye raspbian/debian 11, PHP8.0 + apache2

```
tail -100f /var/log/apache2/error.log
Raspberry Pi 4B2G,  Bullseye raspbian/debian 11, PHP8.0

[Sat Apr 06 06:16:35.428005 2024] [php:warn] [pid 17683] [client 192.168.2.35:54212] PHP Warning:  include_once(): Failed opening '../parse_svxconf.php' for inclusion (include_path='.:/usr/share/php') in /var/www/html/include/config.php on line 55, referer: http://192.168.2.39:8888/node.php
[Sat Apr 06 06:16:35.910227 2024] [php:notice] [pid 17683] [client 192.168.2.35:54212] PHP Notice:  session_start(): Ignoring session_start() because a session is already active in /var/www/html/include/tools.php on line 2, referer: http://192.168.2.39:8888/node.php
[Sat Apr 06 06:16:35.910446 2024] [php:warn] [pid 17683] [client 192.168.2.35:54212] PHP Warning:  include_once(../parse_svxconf.php): Failed to open stream: No such file or directory in /var/www/html/include/config.php on line 55, referer: http://192.168.2.39:8888/node.php
[Sat Apr 06 06:16:35.920412 2024] [php:warn] [pid 17683] [client 192.168.2.35:54212] PHP Warning:  include_once(): Failed opening '../parse_svxconf.php' for inclusion (include_path='.:/usr/share/php') in /var/www/html/include/config.php on line 55, referer: http://192.168.2.39:8888/node.php
[Sat Apr 06 06:16:37.087780 2024] [php:warn] [pid 17683] [client 192.168.2.35:54212] PHP Warning:  include_once(../parse_svxconf.php): Failed to open stream: No such file or directory in /var/www/html/include/config.php on line 55, referer: http://192.168.2.39:8888/node.php
[Sat Apr 06 06:16:37.087874 2024] [php:warn] [pid 17683] [client 192.168.2.35:54212] PHP Warning:  include_once(): Failed opening '../parse_svxconf.php' for inclusion (include_path='.:/usr/share/php') in /var/www/html/include/config.php on line 55, referer: http://192.168.2.39:8888/node.php

```
After I  changed the php config file , another error appear.

 ![image](https://github.com/f5vmr/SVXLink-Dash-V2/assets/22002824/47eda422-42ac-4fbd-9a7f-57ca0ddc18bf)

```
[Sat Apr 06 06:16:38.471155 2024] [php:notice] [pid 17683] [client 192.168.2.35:54212] PHP Notice:  session_start(): Ignoring session_start() because a session is already active in /var/www/html/include/parse_svxconf.php on line 2, referer: http://192.168.2.39:8888/node.php
[Sat Apr 06 06:16:40.194668 2024] [php:notice] [pid 17683] [client 192.168.2.35:54212] PHP Notice:  session_start(): Ignoring session_start() because a session is already active in /var/www/html/include/parse_svxconf.php on line 2, referer: http://192.168.2.39:8888/node.php
```

Can you give me some tips?

Thank you !

**Comment by f5vmr** [comment]
Hi there,
Very strange.
I never have problem installing in every node.
I recommend cd /var/www followed by sudo rm -r html
Then
sudo git clone https://github.com/f5vmr/SVXLink-Dash-V2 html
Remember the space before html

I now use bullseye Debian 12 and PHP 8.2 and it still works great.

There must be installed a working svxlink, as the PHP needs to find all the
svxlink.conf and svxlink.log.

User must be pi, never root....

Perhaps permissions are wrong.... sudo chown www-data:www-data -R
/var/www/html works for me,  sudo chmod 777 -R /var/www/html

For me everything works 100%. A couple of people the dashboard breaks and
the title of the node disappears.

Chris

**Comment by f5vmr** [comment]
Another thing I forgot to mention. I do not make any changes to PHP. Just
the changes to apache2 mentioned in the README.md. I have just helped a new
repeater owner remotely and the dashboard immediately worked.

In a few days I will launch new svxlink installer that will import
dashboard automatically. I am sorting some bugs.
Chris

**Comment by f5vmr** [comment]
http://svxportal-uk.ddns.net:19080/

**Comment by f5vmr** [comment]
This one using Debian 11 and PHP 8.01.... so hope for you.

**Comment by f5vmr** [comment]
Just an observation. I am also seeing the warnings and notice.

I believe it is the way that some of the library functions are being called
when they are already open. In the PHP, there are functions called by
include and some by include_once, and I suspect that this may be causing
the reports. I did not write all the original code so being inexperienced,
I left these functions in place. I suspect that the use of include_once
should replace include, but I need some time to explore the issue. As I see
no errors, only warnings, I have not done so yet.

Chris

**Comment by f5vmr** [comment]
I have found some issues - I have changed the code with respect to the location of the parse_svxconf.php file. Please go to the html folder and sudo git pull. and try again. I also made some changes to the session header.

if (session_status() === PHP_SESSION_NONE) {
    session_start();
}

**Comment by f5vmr** [comment]
The function parse_ini has now been superceded. New dashboard momentarily

**Comment by f5vmr** [comment]
Closed for the moment
